name: divvest
description: Dividend Reinvestment Tracker for Indonesian Stocks
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  sqflite: ^2.3.3
  path: ^1.9.0
  shared_preferences: ^2.3.3
  http: ^1.2.0
  fl_chart: ^1.2.0
  share_plus: ^7.2.1
  file_picker: ^8.0.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.2.19

flutter:
  assets:
    - assets/splash/splash_image.png
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
flutter_native_splash:
  color: "#004d40"
  image: assets/splash/splash_image.png
  fullscreen: true
  android: true
  ios: true
